### ISSUE TITLE
work on launch URL

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#19]
figure out how the URL should be created in order to launch the test suite
combine with single signon 
how are internal UUID and UUID in the flows related

**Comment by boerrookhuiszen** [comment]
In Remindo it is possible to request a URL via the API. This URL can be visited once and is valid for 30 seconds. It will login the user and redirect to the start page of the test. I think you can do the same with LTI but this is will be much easier to implement, since in these flows we don't use LTI for anything else.

We could add an endpoint to request a launch URL. Or add the URL to the GET on `/offerings/{offeringId}/associations`?

**Comment by rrutte** [comment]
This is always a link on an association. Could we do a GET on /associations/{associationId}/url

and provide the url in the consumer section of the response?

**Comment by rrutte** [comment]
GET uitwerken om alleen de URL op te halen op basis van GET icm queryparameters

**Comment by hamrt** [comment]
Waht are best practices for returning specific attributes from a resource? /url or ?url . The URL is not returned in the object itself therfore /url seems most logical.

**Comment by mcginkel** [comment]
Status: to be defined in okapi spec
