### ISSUE TITLE
FLOW 2 offering: duration, start en end time uitwerken

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#4]
Beter uitwerken hoe de duration en start en end uitgewerkt word.
- flexibel?
- - wat op component
- wat betekend endtime? kan starten of moet eindigen
-

**Comment by rrutte** [comment]
Mij lijkt het volgende:

Als je startDate en endDate gebruikt zijn dat de echte harde begin- en eindmomenten van de componentoffering.

Als je flexibleEntryPeriodStart en flexibleEntryPeriodEnd gebruikt geeft dat aan tussen welke  momenten je mag starten. Heb je nog wel de duration nodig. Bijvoorbeeld PT60M (Period Time 60 Minutes) https://datatracker.ietf.org/doc/html/rfc3339 onderaan pagina 12

**Comment by roelgrif** [comment]
Maybe we can use something like:

"otherCodes": [
{
"codeType": "x-joint",
"code": "true"
}
],

**Comment by hamrt** [comment]
@rrutte in the lead for this issue. 3 scenarios

**Comment by rrutte** [comment]
Gebruik  de reguliere startDateTime en endDateTime

Aanvullingen in de consumer:
- entryEndDateTime (eindmoment waarop kandidaat maximaal mag starten (optioneel)
- startOptions (individualStart | triggeredStart)
- durationFrom (startDateTime | individualStartDateTime | triggeredStartDateTime)
- durationUntil (testDuration | endDateTime)

Deze attributen ondersteunen de scenario's zoals zowel in Remindo en TOA ingericht kunnen worden.

**Comment by roelgrif** [comment]
Niet alleen omdat ze dan flexibel uitbreidbaar zijn, maar ook omdat deze elementen niet in de standaard OOAPI aanwezig zijn. Het lijken me wel wat veel elementen voor het omschreven doel. Heel compleet, maar is het geen overkill? M.a.w. kunnen we hier niet ook inconsistentie op krijgen? Bij startDateTime=9:00, endDateTime=12:00, entryEndDateTime=10:00, startOptions = triggeredStart, durationFrom=triggeredStartDateTime, durationUntil=endDateTime, duration = 2 hours?

**Comment by hamrt** [comment]
the offering endpoints now reflect these issues (based on standards in use for time and duration) The extra requested attributes have been put under the consumer element

**Comment by roelgrif** [comment]
I am missing the OtherCodes container for these attributes, am I seeing this correctly?

**Comment by hamrt** [comment]
Yes they are missing and that is on purpose. Since the desired attributes are available in de consumers array. This solution has the requested flexilbility and also offers the use of enumerations for the values of the different attributes. This can not be resolved using the earlier proposed otherCodes solution.  If other solutions are preferable please provide them in the comments so we can figure a way forward.

**Comment by roelgrif** [comment]
OK, I probably missed that last Tuesday. If this is more flexible and offers enumerations, OK. I am just wondering if we are not extending/expanding/stretching the OOAPIv5 too much with this.

**Comment by hamrt** [comment]
Fair point, it is now part of the consumer array. So that reduces its scope. We could in the future look into if we want to load it into the OOAPI overall spec. For now it's only described (and not mandatory) for the MBO-toetsaanmelding consumer

**Comment by roelgrif** [comment]
All right but aren't we diverting more and more from a standard solution to a specific one? The more we put in that specific consumer the less generic our solution will be. Maybe the MBO-toetsaanmelding consumer will eventually land in the OOAPI-v5 specification, it will never get into a world wide EDU-API specification, I presume.

**Comment by roelgrif** [comment]
All right but, if I understand correctly, aren't we diverting more and more from a standard solution to a specific one? The more we put in that specific consumer the less generic our solution will be. Maybe the MBO-toetsaanmelding consumer will eventually land in the OOAPI-v5 specification, it will never get into a world wide EDU-API specification, I presume. 
Sorry, forgot the Reopen button in previous comment.

**Comment by rrutte** [comment]
[Testmoment scenarios.xlsx](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/files/10054961/Testmoment.scenarios.xlsx)

Scenario's are in the file attached. No idea how te get this table into the documentation @hamrt can you do something there?

Based on the discussion on Friday I would say that te attributes we've defined aren't identifiers so a codes section is, although a very flexible way to be prepared for future additions, not really the best place. Maybe we could even state that these attributes are simply missing in de current OO-API spec because the testoffering use-cases haven't been part yet of the scenario's OO-API has been used for.

**Comment by hamrt** [comment]
Als markdown toevoegen in de documentatie van de tabel
