### ISSUE TITLE
Add type to result?

### ISSUE THREAD

**Issue by boerrookhuiszen** [NetwerkExamineringDigitalisering/NED-OOAPI#46]
The Eduarte team uses automatically generated code based on the spec, but it could not parse the example for the `PATCH /associations/{associationId}` request. 

To be able to parse the message, we had to add a type to both `result` and `consumer`, see example below:

```
  "result": {
    "type": "ComponentResult", //ADDED
    "state": "completed",
    "pass": "passed",
    "score": "10",
    "resultDate": "2023-01-30",
    "consumers": [
      {
     "type": "Consumer", //ADDED
        "consumerKey": "MBO-toetsafname",
        "attendance": "present"
      }
    ],
    "weight": 100
  }
}
```

The result is described as ["One of" "ComponentResult"](https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/associations/operation/partialUpdateAssociationById), but this isn't described as type in the spec of in the examples?

**Comment by hamrt** [comment]
This does not look like a viable solution it would break the rest of the models. The type object for consumers is off. Since the consumers itself is an array of consumer objects. the type of consumer is inferred. The ComponentResulttype should probably not be used in the model. An alteration could be to change the PATCH method to include the type of association. That would make the model complete. I'll include a PR for this issue
