### ISSUE TITLE
Review Flow 1

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#54]
The text explaining flow 1 and it's subflows has been modified by me. Please review en share comments.

**Comment by roelgrif** [comment]
I've started the review. I'm seeing in the Consumer2 box an enrollmentAssociation but to me it isn't clear what this exactly means (enrollment on a course? same as courseAssociationID?) and how the TPS is going to get the info connected to this association. Same for the programAssociation, but I see a programOfferingAssociation in the additional info section that might explain that one? Is the difference in these identifiers intentional? Shouldn't we have a courseOfferingAssociation somewhere?

**Comment by roelgrif** [comment]
Another question: about flow 1B: how does the TPS know which groups there are in the SIS (which names/codes)? I guess there should be an endpoint for getting all (relevant) groups? Or should we better make a PUT/PATCH for that to push these group definitions to the TPS?

**Comment by roelgrif** [comment]
BTW, what is meant exactly with 'do everything with plan' in the message scheme diagrams?

**Comment by roelgrif** [comment]
Instead of 'groupCode' I think we should use 'groupId'. I think the endpoint should be GET /groups/{groupId}/persons for that. After that, we have a generic operation for getting info on any specific person GET /persons/{personId} so I am not sure why we would need to get any extra info on a person in the specific context of a group. The person either belongs to the group or not? So the "Sequence diagram of request to get a single student" confuses me.

**Comment by hamrt** [comment]
added commit 75a2d352726378d8d5f7fbc2beb523907b9f96e3 with updated flow 1 to include additional sequnce diagrams as well as group objects

**Comment by JosVanderArend** [comment]
In de eerste opsomming bij flow 1a (https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow1.md#flow-1a--endpoints-for-this-flow) zie ik endpoint **GET /ooapi/offerings/{offeringId}** erbij staan. 
Deze wordt verder niet uitgewerkt of genoemd. Is deze wel nodig als het eerste endpoint de details van een Offering  al teruggeeft (weliswaar in een lijst)?

**Comment by roelgrif** [comment]
Andere vraag: ik zie nu dat er een PUT /a/ooapi/offerings/{offeringId} is in deze flow, maar moet bij  "component":"c5fca27e-ccc1-430d-9888-90e005ad6a86" de <component> niet vervangen worden door <componentId> (volgens de OOAPI)?

**Comment by JosVanderArend** [comment]
Hallo Roel, op jouw vraag "moet "component" niet vervangen worden door "componentId" ", is het antwoord nee. 
Dit is een attribuut van Offering waarbij een identifier (string) of een Component (object) mag worden gebruikt.
